<a href="https://www.kaggle.com/code/joanwachuka/ksl-sign?scriptVersionId=292183987" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_12.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_9.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_21.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_5.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_22.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_16.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_1.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_11.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_3.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_10.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_2.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_18.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_7.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_14.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_15.npy
/kaggle/input/ksl-hand-landmarks/dataset/mother/mother_8.npy
/kaggle/input/k

In [2]:
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout ,Normalization , BatchNormalization, Bidirectional, Input
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

2026-01-16 09:47:41.272318: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1768556861.631187      24 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768556861.760640      24 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768556862.661559      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768556862.661611      24 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768556862.661614      24 computation_placer.cc:177] computation placer alr

In [3]:
# Configuration
DATA_PATH = "/kaggle/input/ksl-hand-landmarks/dataset"
MAX_FRAMES = 60
FEATURES = 126
EPOCHS = 200  
BATCH_SIZE = 4
LEARNING_RATE = 0.001
LABELS = ['a', 'is', 'mother', 'my', 'this'] 

In [4]:
# Load data (no augmentation)
X, y = [], []
for label_idx, label in enumerate(LABELS):
    label_dir = os.path.join(DATA_PATH, label)
    for file in os.listdir(label_dir):
        if file.endswith('.npy'):
            seq = np.load(os.path.join(label_dir, file))
            X.append(seq)
            y.append(label_idx)


print("Number of sequences:", len(X))
print("Example sequence shape:", X[0].shape)

# Convert to arrays
X = np.array(X, dtype=object)
y = np.array(y)


# Pad sequences to make them same length


# Pad sequences
X_padded = pad_sequences(X, maxlen=MAX_FRAMES, dtype='float32', padding='post', truncating='post')
y_onehot = to_categorical(y, num_classes=len(LABELS))
print("X shape after padding:", X_padded.shape)



Number of sequences: 101
Example sequence shape: (23, 126)
X shape after padding: (101, 60, 126)


In [5]:
# Train/val/test split (stratified)
X_train, X_temp, y_train, y_temp = train_test_split(
    X_padded, y_onehot, test_size=0.3, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=np.argmax(y_temp, axis=1)
)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("x_val shape:", X_val.shape)



norm = Normalization(axis=-1)
norm.adapt(X_train)

X_train shape: (70, 60, 126)
X_test shape: (16, 60, 126)
x_val shape: (15, 60, 126)


I0000 00:00:1768556882.332360      24 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15513 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0


In [6]:


# MODEL

model = Sequential([
    # Input layer
        Input(shape=(MAX_FRAMES, FEATURES)),
        
        # Small LSTM with dropout
        Bidirectional(LSTM(32, return_sequences=True)),
        
        
        # Another small LSTM
        LSTM(16, return_sequences=False, dropout=0.3),
        BatchNormalization(),
        
        # Dense layers with regularization
        Dense(1024, activation='relu'),
        Dropout(0.4),
        
        Dense(512, activation='relu'),
        Dropout(0.3),
        
        # Output layer
        Dense(len(LABELS), activation='softmax')
    
    
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)
# Callbacks
callbacks = [
    EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=8, min_lr=1e-6),
    ModelCheckpoint('best_model.keras', monitor='val_accuracy', save_best_only=True, mode='max')
]

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)   │ (None, 60, 64)         │        40,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 16)             │         5,184 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │        17,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 512)            │       524,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 5)              │         2,565 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 590,725 (2.25 MB)

 Trainable params: 590,693 (2.25 MB)

 Non-trainable params: 32 (128.00 B)

In [7]:
# ==============================
# TRAIN
# ==============================
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks,
    verbose=1
)


test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\n✅ Test Accuracy: {test_acc:.4f}")

# Save final model & labels
model.save("ksl_sign_language_model.keras")
np.save("sign_labels.npy", np.array(LABELS))

print("Model and labels saved!")
# ==============================
# SAVE
# ==============================
# Save final model & labels
model.save("ksl_sign_language_model.keras")
np.save("sign_labels.npy", np.array(LABELS))

print("Model and labels saved!")

Epoch 1/200


I0000 00:00:1768556888.211951      67 cuda_dnn.cc:529] Loaded cuDNN version 91002


18/18 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.1373 - loss: 1.6123 - val_accuracy: 0.0667 - val_loss: 1.6087 - learning_rate: 0.0010
Epoch 2/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2963 - loss: 1.5721 - val_accuracy: 0.2000 - val_loss: 1.6079 - learning_rate: 0.0010
Epoch 3/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.2675 - loss: 1.6003 - val_accuracy: 0.2000 - val_loss: 1.6075 - learning_rate: 0.0010
Epoch 4/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.2728 - loss: 1.5978 - val_accuracy: 0.2000 - val_loss: 1.6103 - learning_rate: 0.0010
Epoch 5/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.2795 - loss: 1.6051 - val_accuracy: 0.2000 - val_loss: 1.6100 - learning_rate: 0.0010
Epoch 6/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.1470 - loss: 1.6139 - val_accuracy: 0.2000 - val_loss: 1.6059 - learning_rate: 0.0010
Epoch 7/200
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.2565 - loss: 1.5835 - val_accuracy

In [8]:
# Evaluate
print("\nEvaluating best model...")
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Accuracy: {test_accuracy:.4f}")
print(f"Test Loss: {test_loss:.4f}")

# Predict and show classification report
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

from sklearn.metrics import classification_report, confusion_matrix
print("\nClassification Report:")
print(classification_report(y_true_classes, y_pred_classes, target_names=LABELS))

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_classes, y_pred_classes))


Evaluating best model...
Test Accuracy: 0.9375
Test Loss: 0.2074
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step

Classification Report:
              precision    recall  f1-score   support

           a       1.00      1.00      1.00         4
          is       1.00      0.67      0.80         3
      mother       0.75      1.00      0.86         3
          my       1.00      1.00      1.00         3
        this       1.00      1.00      1.00         3

    accuracy                           0.94        16
   macro avg       0.95      0.93      0.93        16
weighted avg       0.95      0.94      0.94        16


Confusion Matrix:
[[4 0 0 0 0]
 [0 2 1 0 0]
 [0 0 3 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


In [9]:
import numpy as np
from collections import defaultdict

# Convert one-hot y_test back to integers
y_test_int = np.argmax(y_test, axis=1)

# Group indices by class in the test set
indices_by_class = defaultdict(list)
for idx, label in enumerate(y_test_int):
    indices_by_class[label].append(idx)

# Select up to 3 samples per class
selected_indices = []
for label in range(len(LABELS)):
    if label in indices_by_class:
        selected = indices_by_class[label][:3]  # take first 3 (or fewer)
        selected_indices.extend(selected)

# Extract those samples
X_demo = X_test[selected_indices]
y_demo_true = y_test_int[selected_indices]

# Predict
y_demo_pred = model.predict(X_demo)
y_demo_pred_labels = np.argmax(y_demo_pred, axis=1)

# Print results
print("Manual test on 3 samples per class :\n")
for i, idx in enumerate(selected_indices):
    true_label = LABELS[y_demo_true[i]]
    pred_label = LABELS[y_demo_pred_labels[i]]
    confidence = np.max(y_demo_pred[i])
    status = "✅" if true_label == pred_label else "❌"
    print(f"{status} Sample {i+1}: True='{true_label}' | Pred='{pred_label}' | Conf={confidence:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step
Manual test on 3 samples per class :

✅ Sample 1: True='a' | Pred='a' | Conf=0.84
✅ Sample 2: True='a' | Pred='a' | Conf=0.83
✅ Sample 3: True='a' | Pred='a' | Conf=0.88
❌ Sample 4: True='is' | Pred='mother' | Conf=0.46
✅ Sample 5: True='is' | Pred='is' | Conf=0.45
✅ Sample 6: True='is' | Pred='is' | Conf=0.45
✅ Sample 7: True='mother' | Pred='mother' | Conf=0.92
✅ Sample 8: True='mother' | Pred='mother' | Conf=0.91
✅ Sample 9: True='mother' | Pred='mother' | Conf=0.92
✅ Sample 10: True='my' | Pred='my' | Conf=0.99
✅ Sample 11: True='my' | Pred='my' | Conf=1.00
✅ Sample 12: True='my' | Pred='my' | Conf=1.00
✅ Sample 13: True='this' | Pred='this' | Conf=1.00
✅ Sample 14: True='this' | Pred='this' | Conf=0.99
✅ Sample 15: True='this' | Pred='this' | Conf=1.00
